version: "3.8"
services:
  web_ui:
    container_name: web_ui
    build:
      context: ./web_ui
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    command: sh -c "npm install && npm start"
    networks:
      - dockernetw

networks:
  dockernetw:
    driver: bridge

