version: "3.8"
services:
  web_ui:
    container_name: web_ui
    build:
      context: ./web_ui
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./web_ui/:/app/
    command: npm start
    networks:
      - dockernetw